api/database/runSeed.ts, api/database/seed.ts, package.json
=> Fix seeding

.github/workflows/deploy.yml, api/utils/services.factory.ts, config.ts, config.types.d.ts, ecosystem.config.js, nuxt.config.ts, plugins/apollo.ts
=> Fix and improve deployment workflow using environments

components/t-alert.stories.ts, components/t-button.stories.ts, components/t-checkbox.stories.ts, components/t-dropdown.stories.ts, components/t-input-group.stories.ts, components/t-nuxtlink.stories.ts, components/t-select.stories.ts, components/t-table.stories.ts, components/t-tag.stories.ts, components/t-textarea.stories.ts
Added stories for all of the available components.
=> Add storybook stories for remaining tailwind components

.eslintrc.cjs, nuxt.config.ts, patches/@apollo+client+3.6.9.patch, patches/@vue+apollo-composable+4.0.0-alpha.18.patch, patches/@vue+apollo-util+4.0.0-alpha.18.patch, patches/h3+0.7.10.patch, plugins/fontawesome.ts, server/user/auth.service.ts, yarn.lock
Mainly to include the fix https://github.com/isaacs/node-lru-cache/commit/7bbe83c8e6df2d3a1643f2f49f250d9df970fe6e
=> Update package lock file

nuxt.config.ts, package.json, server/documents/integration.test.ts, server/index.ts, server/schema.ts, server/user/integration.test.ts, test/apollo.server.ts, types/schims-graphql.d.ts
Problem is that graphql files are not moved to generated server files.
=> Load graphql schema as virtual module

.github/workflows/azure-static-web-apps-mango-pebble-0224c3803.yml
https://github.com/dependabot/dependabot-core/issues/3253
=> Use pull_request_target to make secrets available to dependabot

.github/workflows/deploy.yml, config.ts, nuxt.config.ts, server/utils/services.factory.ts
Fix that redis is not defined during build (prerender phase) on Azure.
=> Fix build on Azure

.github/workflows/deploy.yml, package.json, patches/nitropack+0.4.24.patch
And disable failure for API tests for now on deployment
=> Fix definition of routes on azure

components/LandingPageGetInvolved.vue
=> Display maintainers in a popover

.github/workflows/deploy.yml
This is no longer necessary: https://github.com/unjs/nitro/pull/479
=> Remove obsolete deploy steps

plugins/apollo.ts
=> chore: add graphql client identification

.github/workflows/deploy.yml, apollo/apollo-server.ts, nuxt.config.ts, server/index.ts, server/postman/TestSuite.json
At least apollo studio is now working with both the local and azure endpoint.
=> chore: fix cors headers

.github/workflows/deploy.yml
Prisma, and maybe other packages, need to be run on the same system as they are build.
=> chore: run deploy workflow on windows

.github/workflows/deploy.yml
Azure/static-web-apps-deploy is a container action and thus doesn't work on windows.
=> chore: manually deploy to azure

.github/scripts/deploy.py
Has better cold-start performance and faster deployment (from 3.5 min to 0.5min). https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#integration-with-zip-deployment
=> chore: run azure functions from package file

.eslintrc.cjs, apollo/validation.ts, composables/zodForm.ts, package.json, pages/user/login.vue, server/user/resolvers.ts, yarn.lock
Fixes #139, at least in the sense that the infrastructure is now set-up. However, some other forms still need to be endowed with validation.
=> feat: add client-side validation to login

content/surveys/2015/index.md, content/surveys/index.md, modules/redirects.ts, nuxt.config.ts, pages/surveys/2015/[...slug].vue
=> feat: add redirects for backwards compatibility

README.md
=> docs: add url for login

README.md, server/database/seed.ts, server/user/e2e.test.ts, server/user/integration.test.ts, test/api-e2e/supertest.ts
=> fix: use correct 'org' domain instead of 'de' for test data

.eslintrc.cjs, components/DocumentEditor.vue, components/DocumentView.vue, components/SideBar.vue, pages/dashboard.vue
Now that https://github.com/B2o5T/graphql-eslint/issues/480 is fixed.
=> chore: enable eslint for vue files

.vscode/settings.json, components/DocumentEditor.vue, components/DocumentView.vue, server/database/integration.test.ts, server/database/migrations/20221024192239_/migration.sql, server/database/schema.prisma, server/database/seed.ts, server/documents/integration.test.ts, server/documents/resolvers.spec.ts, server/documents/resolvers.ts, server/documents/schema.graphql, server/documents/user.document.service.spec.ts, server/documents/user.document.service.ts, server/user/resolvers.ts, test/util.ts
=> feat: implement persons (authors, editors, ...) following CSL standard

components/LandingPageDownload.vue, components/LandingPageFeatures.vue, components/LandingPageGetInvolved.vue, pages/index.vue, tailwind.config.ts
=> feat: improve look of landing page

nuxt.config.ts, package.json, yarn.lock
Now that https://github.com/nuxt/nuxt/issues/13843 is resolved.
=> chore: replace nuxt-runtime-compiler by builtin nuxt feature

nuxt.config.ts, package.json, pages/user/login.vue, yarn.lock
https://vee-validate.logaretm.com/v4/integrations/nuxt/
=> chore: use vee-validate/nuxt module for auto imports

components/NavBar.vue, composables/screen.ts, layouts/content.vue, nuxt.config.ts
=> fix: improve ssr of navigation header

layouts/content.vue, nuxt.config.ts, package.json, yarn.lock
Fixes #479.
Follow-up: 
- Remove `site-name` and `site-description` from `SeoKit` component once https://github.com/harlan-zw/nuxt-seo-kit/issues/56 is fixed
- Specify title of root as as `JabRef - Free Reference Manager - Stay on top of your Literature` (while keeping `site-name=JabRef`) once https://github.com/harlan-zw/nuxt-seo-kit/issues/57 is fixed
=> chore: add sitemap and robots

components/NavBar.vue, pages/index.vue
=> feat: improve look and feel for navbar hamburger

layouts/content.vue
=> fix: add priceCurrency to structured data to improve seo

.github/workflows/deploy.yml
fixes deployment, closes https://github.com/JabRef/JabRefOnline/issues/1828
=> chore: use OpenID connect for azure login

app.vue, nuxt.config.ts, package.json, tsconfig.json, yarn.lock
Migrate from [huntersofbook/naive-ui-nuxt](https://github.com/huntersofbook/naive-ui-nuxt) to [becem-gharbi/nuxt-naiveu](https://github.com/becem-gharbi/nuxt-naiveui). Mainly because it fixes the problem with the background of the download button, but also because it seems to be more mature and plans to extend beyond being a simple nuxt wrapper (see https://github.com/becem-gharbi/nuxt-naiveui/issues/9).
=> fix: fix download button background by using different naive-ui nuxt module

.github/dependabot.yml
=> chore: add more packages to merge groups

nuxt.config.ts
https://github.com/nuxt/cli/issues/193
The commit removes a workaround for a specific issue with Nuxt.js. The issue has been resolved, so the workaround is no longer necessary.
=> chore: remove workaround for Nuxt.js issue not exiting build

package.json, pnpm-lock.yaml
Following https://github.com/pnpm/pnpm/pull/8337.
=> chore: apply dependency patches to all versions

renovate.json5
=> chore: improve renovate scheduling

.github/workflows/deploy-preview.yml
=> chore: add `NUXT_SESSION_PASSWORD` secret to ci

renovate.json5
Reason: breaks until migration to v9, and may be replaced by oxlint in the relatively near future
=> chore: disable renovate updates for eslint-packages

server/api/getLatestRelease.ts
=> fix: filter out prereleases when getting the latest release

.github/workflows/deploy.yml
Should hopefully fix that the web apps are getting stuck in 'deleting'.
=> chore: try direct deployment without prior deletion of the web app

.github/workflows/deploy-preview.yml, .github/workflows/deploy.yml, renovate.json5
=> chore: update Python version in GitHub Actions workflows to 3.13

.github/scripts/deploy.py, .github/workflows/deploy-preview.yml, .github/workflows/deploy.yml
=> chore: always delete existing function apps

.vscode/settings.json, renovate.json5
=> chore: run `pnpm dedupe` during Renovate updates

package.json, pnpm-lock.yaml
=> chore: use jiti to run db seed

chromatic.config.json
=> chore: add buildScriptName to chromatic configuration

.github/workflows/ci.yml, renovate.json5
=> chore: upgrade Node used on Azure to v22

.github/scripts/deploy.py
=> chore: fix Node version on Azure

.github/workflows/deploy-preview.yml, .github/workflows/deploy.yml
=> chore: temporarily disable email test

.github/workflows/copilot-setup-steps.yml
=> chore: fix copilot env setup
